# Generated by Django 5.0.6 on 2026-07-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_photo_url',
            field=models.URLField(help_text='Supabase URL of the bill photo. Required — no photo = no bill.'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='material_type',
            field=models.CharField(blank=True, default='other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. bags, cubic meters, kg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='unit_price_lkr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
