# Generated by Django 5.0.6 on 2026-07-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progresslog_tomorrow_status_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='tomorrow_plan',
            field=models.TextField(blank=True, help_text='Free-text plan of what the team intends to do tomorrow.', null=True),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='blockers',
            field=models.CharField(blank=True, choices=[('material_shortage', 'Material Shortage'), ('worker_noshow', 'Workers Did Not Show Up'), ('equipment_fault', 'Equipment Fault'), ('rain', 'Rain'), ('awaiting_owner', 'Awaiting Owner Decision'), ('other', 'Other')], help_text='Primary reason if work was impeded.', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='progresslog',
            name='work_done_today',
            field=models.TextField(help_text='Free text description of work completed today.'),
        ),
    ]
