# Generated by Django 5.0.6 on 2026-07-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='absent_reason',
            field=models.CharField(blank=True, choices=[('sick', 'Sick / Medical'), ('personal', 'Personal Leave'), ('no_show', 'Did Not Show Up'), ('rain', 'Rain Day'), ('other_site', 'Working at Another Site'), ('terminated', 'No Longer Employed'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Was cash payment made today?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(help_text='e.g. Mason, Labourer, Electrician', max_length=100),
        ),
    ]
